<template>
<div>
  dataOverview正在研发中...
  dataOverview正在研发中...
  dataOverview正在研发中...
  dataOverview正在研发中...
  dataOverview正在研发中...
  dataOverview正在研发中...
  dataOverview正在研发中...
  dataOverview正在研发中...
</div>
</template>

<script>
export default {
  name: "dataOverview"
}
</script>

<style scoped>
  
</style>